apiVersion: v1
kind: Secret
metadata:
  name: idp-secrets
type: Opaque
stringData:
  POSTGRES_USER: "replace-me"
  REDIS_HOST: "replace-me"
  POSTGRES_PASSWORD: "replace-me"
  JWT_SECRET: "replace-me"