apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wss-ap
  template:
    metadata:
      labels:
        app: wss-ap
    spec:
      containers:
      - name: wss-app
        image: 187457215475.dkr.ecr.ap-south-1.amazonaws.com/wss-app:6b70054c9dc64eade4b9b439a7f7b226b0691592
        ports:
        - containerPort: 80