apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wss-ap
  template:
    metadata:
      labels:
        app: wss-ap
    spec:
      containers:
      - name: wss-app
        image: 187457215475.dkr.ecr.ap-south-1.amazonaws.com/wss-app:d41423bfa3c1504c11254f9ba84fe0d8b891f3ea
        ports:
        - containerPort: 80