apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wss-ap
  template:
    metadata:
      labels:
        app: wss-ap
    spec:
      containers:
      - name: wss-app
        image: 187457215475.dkr.ecr.ap-south-1.amazonaws.com/wss-app:c0c88063f09be7d82f0cf7a03664c4e9d63b51f1
        ports:
        - containerPort: 80