apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: idp-secrets
  namespace: idp

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: SecretStore

  target:
    name: idp-secrets
    creationPolicy: Owner

  data:

    - secretKey: POSTGRES_HOST
      remoteRef:
        key: idp/prod/app
        property: POSTGRES_HOST

    - secretKey: POSTGRES_PORT
      remoteRef:
        key: idp/prod/app
        property: POSTGRES_PORT

    - secretKey: POSTGRES_DB
      remoteRef:
        key: idp/prod/app
        property: POSTGRES_DB

    - secretKey: POSTGRES_USER
      remoteRef:
        key: idp/prod/app
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: idp/prod/app
        property: POSTGRES_PASSWORD

    - secretKey: REDIS_HOST
      remoteRef:
        key: idp/prod/app
        property: REDIS_HOST

    - secretKey: SQS_DLQ_URL
      remoteRef:
        key: idp/prod/app
        property: SQS_DLQ_URL

    - secretKey: SQS_JOBQ_URL
      remoteRef:
        key: idp/prod/app
        property: SQS_JOBQ_URL