apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-worker
  template:
    metadata:
      labels:
        app: idp-worker
    spec:
      containers:
        - name: worker
          image: 187457215475.dkr.ecr.ap-south-1.amazonaws.com/idp-worker:79cfd26
          envFrom:
            - configMapRef:
                name: idp-config
            - secretRef:
                name: idp-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
